### ISSUE TITLE
Criar label hacktoberfest

### ISSUE THREAD

**Issue by leogregianin** [juniorabranches/react-repo-git-info#10]
Criar o label hacktoberfest => https://hacktoberfest.digitalocean.com

1 - Dentro da página de Issues, acessar o botão "Labels".
2 - Acessar o botão verde "New label".
3 - Inserir o label "hacktoberfest", escolher a cor e "Create label".
4 - Acessar cada issue e incluir a nova label.

**Comment by juniorabranches** [comment]
Adicionado label "hacktoberfest"
