### ISSUE TITLE
Atualizar versão do React

### ISSUE THREAD

**Issue by leogregianin** [juniorabranches/react-repo-git-info#8]
Atualizar o React para última versão. Hoje 16.0, amanhã não sei.

Warnings:

`bundle.js:4980 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class`

`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs`

**Comment by fanny** [comment]
React.PropTypes has moved into a different package since React v15.5. Please use the prop-types library instead. 
https://www.npmjs.com/package/prop-types
