### ISSUE TITLE
Erro na busca do usuário

### ISSUE THREAD

**Issue by leogregianin** [juniorabranches/react-repo-git-info#9]
Se o username da pesquisa for inválido, pegar o error catch e mostrar mensagem na tela.

**Comment by leogregianin** [comment]
Testar a validação quando não informado usuário e quando informado, o usuário for inválido.

**Comment by LeoCp** [comment]
Posso pegar essa

**Comment by leogregianin** [comment]
@LeoCp a vontade :D

**Comment by renanrboliveira** [comment]
Eae @LeoCp deu certo? Se não tiver fazendo eu posso pegar =)

**Comment by LeoCp** [comment]
Ja tinha feito, esqueci de mandar hehe
